### ISSUE TITLE
Typo in the repository name

### ISSUE THREAD

**Issue by Andarist** [albertfdp/react-resilient#2]
There is no such thing as `resilent`, appropriate would be `resilient`. I think this is what you were aiming to. 

Great utility, exactly what I wanted to do after React v16 gets shipped.

**Comment by albertfdp** [comment]
This is now fixed. Thanks!

However it broke the old GH page url :( I tried creating a repo with the old name and just adding the same page, but no luck. https://github.com/albertfdp/react-resilent/tree/gh-pages

**Comment by albertfdp** [comment]
Ok, it works now :)
